config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  root 'welcome#index'
  
  get    'signup', to: 'users#new'
  get    'login' , to: 'sessions#new'
  post   'login' , to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  get    'ranking/have', to: 'ranking#have', as: 'ranking_have'
  get    'ranking/want', to: 'ranking#want', as: 'ranking_want'
  get    'message_boards', to: 'message_boards#index' , as: 'general_board'
  
  resources :users do
    get 'message_boards', to: 'users#message_boards', as: 'message_boards'
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :items, only: [:new, :show]
  resources :ownerships, only: [:create, :destroy]
  resources :message_boards, only: [:create, :show, :destroy] do
    resources :messages, only: [:create, :edit, :update, :destroy]
  end

end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :user, class_name: "User"
  belongs_to :message_board, class_name: "MessageBoard"
  validates :user_id, presence: true
  validates :message_board_id, presence: true
  validates :content, presence: true, length: { maximum: 200 }
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
    before_action :logged_in_user, only: [:create, :edit]
    before_action :set_message, only: [:edit, :update]
    
    def create
        @message = current_user.messages.build(message_params)
        
        if @message.save
            flash[:success] = "Message created!"
            redirect_to :back
        else
            flash[:danger] = "Failed to create!!"
            redirect_to :back
        end
    end
    
    def destroy
        @message = current_user.messages.find_by(id: params[:id])
        return redirect_to :back if @message.nil?
        @message.destroy
        flash[:success] = "Message deleted"
        redirect_to :back
    end
    
    def edit
    end
    
    def update
        if @message.update(message_params)
            # 保存に成功した場合は掲示板ページへリダイレクト
            redirect_to message_board_path(id: params[:message_board_id]), notice: "メッセージを編集しました。"
        else
            #保存に失敗した場合は編集画面へ戻す
            render 'edit'
        end
    end
    
    private
    def message_params
        params.require(:message).permit(:message_board_id, :content)
    end
    
    def set_message
        @message = Message.find(params[:id])
    end
end

app/views/messages/_edit_message.html.erb
<div class="container message_board_form">
  <div class="col-md-8 col-md-offset-2">
    <div class="row">
      <div class="form-top">
        <h2>編集</h2>
      </div>
      <%= form_for(message , url: message_board_message_path(message_board_id: message_board.id, id: message.id)) do |f| %>
        <%= render 'shared/error_messages', object: f.object %>
        <div class="form-group">
          <%= f.hidden_field :message_board_id, value: message_board.id %>
        </div>
        <div class="form-group">
          <label>content</label>
          <%= f.cktext_area :content, class: "form-control" %>
        </div>
        <div class="submit-group">
          <%= f.submit "Post", class: "btn btn-primary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/messages/_post_message.html.erb
<% if logged_in? %>
  <div class="container message_board_form">
    <div class="col-md-8 col-md-offset-2">
      <div class="row">
          <div class="form-top">
              <h2>新規作成</h2>
          </div>
          <p><span class="content">Content</span></p>
          <%= form_for(message , url: message_board_messages_path(message_board_id: message_board.id)) do |f| %>
            <%= render 'shared/error_messages', object: f.object %>
            <div class="form-group">
              <%= f.hidden_field :message_board_id, value: message_board.id %>
            </div>
            <div class="form-group">
              <%= f.cktext_area :content, class: "form-control", placeholder: "input message" %>
            </div>
            <div class="submit-group">
            <%= f.submit "Post", class: "btn btn-primary" %>
            </div>
          <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/messages/edit.html.erb
<h1 align="center">メッセージの編集</h1>

<%= render 'edit_message' , { message: @message, message_board: @message.message_board } %>