config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  root 'welcome#index'
  
  get    'signup', to: 'users#new'
  get    'login' , to: 'sessions#new'
  post   'login' , to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  get    'ranking/have', to: 'ranking#have', as: 'ranking_have'
  get    'ranking/want', to: 'ranking#want', as: 'ranking_want'
  get    'message_boards', to: 'message_boards#index' , as: 'general_board'
  
  resources :users do
    get 'message_boards', to: 'users#message_boards', as: 'message_boards'
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :items, only: [:new, :show]
  resources :ownerships, only: [:create, :destroy]
  resources :message_boards, only: [:create, :show, :destroy] do
    resources :messages, only: [:create, :edit, :update, :destroy]
  end

end

app/views/layouts/_footer.html.erb
<footer>
  <div class="copyright">© <%= Date.today.year %> Let's use.</div>
</footer>

app/views/layouts/_header.html.erb
<header>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container-fruid">
            <div class="navbar-inner">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse-1" aria-expanded="false">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <div class="logo">
                        <%= link_to "Let's use", root_path, class: "navbar-brand" %>
                    </div>
                </div>
                
                <div class="collapse navbar-collapse" id="navbar-collapse-1">
                    <ul class="nav nav-pills navbar-nav navbar-right">
                        <% unless logged_in? %>
                            <li><%= link_to "新規登録", signup_path %></li>
                            <li><%= link_to "ログイン", login_path %></li>
                        <% else %>
                            <li>
                                <%= link_to new_item_path do %>
                                  <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
                                  アイテムを追加
                                <% end %>
                            </li>
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                                    <span class="gravatar">
                                        <%= gravatar_for current_user , size: 20 %>
                                    </span>
                                    <%= current_user.name %>
                                    <span class="caret"></span>
                                </a>
                                <ul class="dropdown-menu">
                                    <li>
                                        <%= link_to "プロフィール" , current_user  %>
                                    </li>
                                    <li role="separator" class="divider"></li>
                                    <li>
                                        <%= link_to "ログアウト", logout_path, method: "delete" %>
                                    </li>
                                </ul>
                            </li>
                        <% end %>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                MessageBoard <b class="caret"></b>
                            </a>
                            <ul class="dropdown-menu">
                                <li>
                                  <%= link_to "General" , general_board_path  %>
                                </li>
                                <% if logged_in? %>
                                    <li>
                                      <%= link_to "My MessageBoard", user_message_boards_path(user_id: current_user.id) %>
                                    </li>
                                <% end %>
                            </ul>
                        </li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                Ranking <b class="caret"></b>
                            </a>
                            <ul class="dropdown-menu">
                                <li>
                                  <%= link_to "Haved Ranking" , ranking_have_path  %>
                                </li>
                                <li>
                                  <%= link_to "Wanted Ranking", ranking_want_path %>
                                </li>
                            </ul>
                        </li>                        
                    </ul>
                </div>
            </div>
        </div>
    </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <% if content_for?(:head) %>
      <%= yield :head %>
    <% else %>
      <title>Let's use!!</title>
    <% end %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no" />
  </head>
  <body>
  
  <%= render partial: "layouts/header" %>
    <% if notice %>
      <div class="alert alert-info", align="center">
        <%= notice %>
      </div>
    <% end %>
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>", align="center">
        <%= message %>
      </div>
    <% end %>
  <%= yield %>
  <%= render partial: "layouts/footer" %>
  
  </body>
</html>